config/routes.rb
Rails.application.routes.draw do

  get  '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/:provider/callback', to: 'sessions#create'
  get  '/auth/failure', to: 'sessions#failure'
  get  '/auth/logout', to: 'sessions#destroy'

  resources :tickets

  get  '/', to: 'tickets#index'
  get  '/css', to: 'css#index'
  post '/tickets/comment', to: 'tickets#comment'
  post '/tickets/upload', to: 'tickets#upload'
  get  '/tickets/download/:id', to: 'tickets#download', as: :download_attachment
  get  'webhook' => 'webhooks#index', as: :webhook
  post 'webhook' => 'webhooks#new', as: :webhook_new
  get  'login' => 'users#index', as: :login
  get  'logout' => 'sessions#destroy', as: :logout
  post 'check-login' => 'users#check_login', as: :check_login

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user

  has_many :user_tickets
  has_many :users, through: :user_tickets

  has_many :transactions

  has_many :tickets, :class_name => "TicketLinked", :foreign_key => :ticket_id
  has_many :followers, :class_name => "TicketLinked", :foreign_key => :follower_id

  @@opened_statuses = ['unscheduled', 'unstarted', 'started', 'finished', 'delivered']
  cattr_reader :opened_statuses

  @@closed_statuses = ['accepted', 'rejected']
  cattr_reader :closed_statuses

  @@all_statuses = Array.new @@opened_statuses
  @@all_statuses.concat @@closed_statuses
  cattr_reader :all_statuses

  # aliases for the statuses in case their names can drive to confussion
  @@alias_opened_statuses = ['unscheduled', 'unstarted', 'started', 'finished', 'delivered']
  cattr_reader :alias_opened_statuses

  @@alias_closed_statuses = ['solved', 'rejected']
  cattr_reader :alias_closed_statuses

  @@alias_all_statuses = Array.new @@alias_opened_statuses
  @@alias_all_statuses.concat @@alias_closed_statuses
  cattr_reader :alias_all_statuses

  @@max_name = 3000
  cattr_reader :max_name

  @@max_description = 15000
  cattr_reader :max_description

  @@max_comment = 15000
  cattr_reader :max_comment

  @@severities = ['low', 'medium', 'high']
  cattr_reader :severities

  @@icon = [":smile:", ":sweat_smile:", ":sweat:"]
  cattr_reader :icon

  def self.get_icon(severity)
    @@icon[@@severities.find_index(severity)]
  end

  def self.validate(name, description)
    errors = nil

    if name.length == 0 or name.length > @@max_name or description.length == 0 or description.length > @@max_description
      errors = []
      if description.length > @@max_description
        errors.push({"field" => "description", "problem" => "Description can not exceed #{@@max_description} characters."})
      elsif description.length == 0
        errors.push({"field" => "description", "problem" => "Description is required."})
      end

      if name.length > @@max_name
        errors.push({"field" => "name", "problem" => "The title can not exceed #{@@max_name} characters."})
      elsif name.length == 0
        errors.push({"field" => "name", "problem" => "The title is required."})
      end
    end

    {errors: errors}
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  include TicketModule
  include UtilModule

  before_filter :check_login
  before_filter :default_header

  # GET: shows the list of tickets
  def index
    @statuses = Ticket.all_statuses
    @alias_statuses = Ticket.alias_all_statuses

    @team = if session[:team].nil? then 'all' else session[:team] end
    @sort_by = if session[:sort_by].nil? then 'newest' else session[:sort_by] end
    @status = if session[:status].nil? then 'opened' else session[:status] end
    @show = if session[:show].nil? then 'mine' else session[:show] end

    unless params[:team].nil?
      @team = params[:team]
      session[:team] = params[:team]
    end

    unless params[:sortby].nil?
      @sort_by = params[:sortby]
      session[:sort_by] = params[:sortby]
    end

    unless params[:status].nil?
      @status = params[:status]
      session[:status] = params[:status]
    end

    unless params[:show].nil?
      @show = params[:show]
      session[:show] = params[:show]
    end

    @opposite_status = if @status=='opened' then 'closed' else 'opened' end

    @bugs = get_all

    @total = @bugs.length

    # filter my tickets
    if @show == 'mine'
      tickets = Ticket.where(user_id: session[:user]["id"]).select("ticket_id")
      @total = tickets.length

      @bugs = filter_by_tickets tickets, @bugs, @status=='opened'
    else
      @bugs = filter_by_status @bugs, @status=='opened'
    end

    if @sort_by == 'state'
      @bugs = sort_tickets_by_state @bugs
    else
      @bugs = sort_tickets_by_last_update @bugs
    end

    # filter by team
    filter = filter_by_team @team, @bugs
    @bugs = filter[:list]
    @numbers = filter[:numbers]

  end

  # GET: shows to the user the form to create a new ticket
  def new
    @browser = users_browser
    @ticket = {}
    if not flash[:errors].nil?
      @errors = flash[:errors]
      @ticket = flash[:ticket]
    end
  end

  # POST: validates and creates a new ticket
  def create
    @browser = users_browser
    ticket = params[:tickets]

    parameters = {
      name: ticket[:name],
      description: ticket[:description],
      labels: [ticket[:team], ticket[:severity]],
      team: ticket[:team],
      severity: ticket[:severity]
    }

    unless ticket[:file_attachments].nil? or ticket[:file_attachments] ==  "" or ticket[:file_attachments] ==  "[]"
      parameters[:attachments] = ActiveSupport::JSON.decode(ticket[:file_attachments])
    end

    result = store_ticket parameters

    unless result.nil? or result[:errors].nil?
      @ticket = result[:ticket]
      @ticket["name"] = @ticket[:name] if @ticket["name"].nil? and not @ticket[:name].nil?
      @ticket["description"] = @ticket[:description] if @ticket["description"].nil? and not @ticket[:description].nil?
      @errors = result[:errors]
      @attachments = ticket[:file_attachments]

      render 'new'
    else
      session[:status] = 'opened'
      redirect_to tickets_path
    end

  end

  # GET: shows to the user the edit form for a given ticket
  def edit
    @browser = users_browser
    unless flash[:errors].nil?
      @errors = flash[:errors]
      @ticket = flash[:ticket]
    else
      @ticket = get_ticket params[:id], true
    end
  end

  # PUT: updates a ticket using the given data
  def update
    @browser = users_browser
    @errors = nil
    @ticket = params[:tickets]

    parameters = {
      name: @ticket[:name],
      description: @ticket[:description],
      labels: [@ticket[:team], @ticket[:severity]]
    }

    result = update_ticket params[:id], parameters

    unless result.nil? or result[:errors].nil?
      @errors = result[:errors]
      @ticket = result[:ticket]
      @ticket["id"] = params[:id]
      @ticket["name"] = parameters[:name]
      @ticket["description"] = parameters[:description]
      @ticket["labels"] = []

      parameters[:labels].each do |label|
        @ticket["labels"].push({"name" => label})
      end

      render 'edit'
    else
      redirect_to ticket_path id: params[:id]
    end
  end

  # GET: shows the content of a ticket
  def show
    # add the user ID to know who wrote this message
    @ticket = get_ticket params[:id]
    ticket = Ticket.find_by ticket_id: params[:id]

    @statuses = Ticket.all_statuses
    @alias_statuses = Ticket.alias_all_statuses

    @errors = nil
    @comment = {
      "text" => "",
      "attachments" => ""
    }

    @user = nil
    unless ticket.nil?
      @user = User.find_by id: ticket[:user_id] unless ticket['user_id'].nil?

      if @user.nil? and @ticket["owners"].length > 0
        @user = {
          name: @ticket["owners"][0]["name"],
          email: @ticket["owners"][0]['email']
        }
      end
    end
  end

  # POST: a user sends a comment
  def comment
    data = {
      project_id: params[:ticket][:project_id],
      story_id: params[:ticket][:id],
      text: params[:comment][:text]
    }

    unless params[:comment][:file_attachments].nil? or params[:comment][:file_attachments] == "" or params[:comment][:file_attachments] ==  "[]"
      data[:file_attachments] = ActiveSupport::JSON.decode(params[:comment][:file_attachments])
      data[:text] = "Attached a file" if data[:text].empty?
    end

    result = store_comment(data)

    # if it didn't work for any reason, the page will be rendered instead of
    # redirecting, because PT accepts huge lengths of characters and overflows the cookie size
    unless result[:errors].nil?
      flash = result
      @errors = result[:errors]
      @comment = {
        "text" => params[:comment][:text],
        "attachments" => params[:comment][:file_attachments]
      }

      # add the user ID to know who wrote this message
      @ticket = get_ticket params[:ticket][:id]
      ticket = Ticket.find_by ticket_id: params[:ticket][:id]

      @statuses = Ticket.all_statuses
      @alias_statuses = Ticket.alias_all_statuses

      @user = nil
      unless ticket.nil?
        @user = User.find_by id: ticket[:user_id] unless ticket['user_id'].nil?

        if @user.nil? and @ticket["owners"].length > 0
          @user = {
            name: @ticket["owners"][0]["name"],
            email: @ticket["owners"][0]['email']
          }
        end
      end

      render 'show'
    else
      redirect_to ticket_path id: params[:ticket][:id]
    end

  end

  # Uploads the files to the Pivotal Tracker server and returns the data
  def upload
    attachments = params[:attachments]
    list = []
    result = []
    unless attachments.is_a?(Array)
      list.push attachments
    else
      list = attachments
    end

    list.each do |file|
      path_data = file.tempfile.path.split '/'
      path_data[path_data.length-1] = file.original_filename

      f = File.join("public", file.original_filename)
      FileUtils.cp file.tempfile.path, f
      tfile = File.open(f)

      result.push upload_file tfile, true
    end

    render :json => result.to_json
  end

  # GET: retrieves a file from PT and sends it to the user
  def download
    # if the ID exists, download the file and then will be sent
    file_data = download_file params[:id]
    extension = file_data[:filename].split('.').last
    file = Tempfile.new([file_data[:filename], ".#{extension}"], Rails.root.join('tmp'))
    file.binmode
    file.write(file_data[:content])
    file.close

    send_file file.path, disposition: 'inline'
  end

  private

  # POST: checks if a user is logged in
  def check_login
    if cookies[:auth_token].nil? or session[:user].nil?
      cookies.delete(:auth_token)
      session[:user] = nil
      redirect_to login_path
    end

    if not session[:user].nil?
      access_token = AccessToken.find_by({token: cookies[:auth_token], user_id: session[:user]["id"]})
      if access_token.nil?
        cookies.delete(:auth_token)
        session[:user] = nil
        redirect_to login_path
      end
    end

  end

  def default_header
    Unirest.default_header('X-TrackerToken', ENV['PIVOTAL_TOKEN'])
    Unirest.default_header('Content-Type', 'application/json')
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def time_diff(last, now = nil)
    now = Time.now if now.nil?

    diff = now - last

    if (diff / 1.year).round > 0
      years = (diff / 1.year).round
      "#{years} year#{'s' if years>1}"
    elsif (diff / 1.month).round > 0
      months = (diff / 1.month).round
      "#{months} month#{'s' if months>1}"
    elsif (diff / 1.day).round > 0
      days = (diff / 1.day).round
      "#{days} day#{'s' if days>1}"
    elsif (diff / 1.hour).round > 0
      hours = (diff / 1.hour).round
      "#{hours} hour#{'s' if hours>1}"
    elsif (diff / 1.minute).round > 0
      minutes = (diff / 1.minute).round
      "#{minutes} minute#{'s' if minutes>1}"
    else
      seconds = (diff / 1.second).round
      "#{seconds} second#{'s' if seconds!=1}"
    end

  end
end

app/views/tickets/_comment.html.erb
<div class="comment">
  <strong>User: <%= data["person_id"] %></strong>
  <div><%= data["text"] %></div>
</div>

app/views/tickets/_history_line.html.erb
<div class="<%= data['action_type'] %>">
  <!-- @TODO define better when webhooks are properly selected -->
  <% case data["action_type"] 
      when "creation" %>Created
  <%  when "status_change" %>Status changed to <strong><%= data['status'] %></strong>
  <% end %>
</div>

app/views/tickets/index.html.erb
<nav id="main-menu" class="fit-height hidden">
  <div>
    <header>
      <button class="main-menu-button" type="button">Close</button>
    </header>
    <h1>Tickets</h1>
    <ul>
      <li>
        <div class="<%= 'active' if @team == 'all' %>" data-team="all">
          <%= link_to "All Tickets(#{@numbers[:all].to_s})", tickets_path(:team=>'all', :status=>@status, :sort_by=>@sort_by, :show=>@show) %>
        </div>
      </li>
      <li>
        <div class="<%= 'active' if @team == 'ios' %>" data-team="ios">
          <%= link_to "iOS (#{@numbers[:ios].to_s})", tickets_path(:team=>'ios', :status=>@status, :sort_by=>@sort_by, :show=>@show) %>
        </div>
      </li>
      <li>
        <div class="<%= 'active' if @team == 'android' %>" data-team="android">
          <%= link_to "Android (#{@numbers[:android].to_s})", tickets_path(:team=>'android', :status=>@status, :sort_by=>@sort_by, :show=>@show) %>
        </div>
      </li>
      <li>
        <div class="<%= 'active' if @team == 'platform' %>" data-team="platform">
          <%= link_to "Platform (#{@numbers[:platform].to_s})", tickets_path(:team=>'platform', :status=>@status, :sort_by=>@sort_by, :show=>@show) %>
        </div>
      </li>
      <li>
        <div class="<%= 'active' if @team == 'web' %>" data-team="web">
          <%= link_to "Web (#{@numbers[:web].to_s})", tickets_path(:team=>'web', :status=>@status, :sort_by=>@sort_by, :show=>@show) %>
        </div>
      </li>
    </ul>
    <div>
      <% if @show != 'all' %>
        <%= link_to tickets_path(:team=>@team, :status=>@status, :sort_by=>@sort_by, :show=>'all') do %>
          <i class="glyphicon glyphicon-check"></i>
          Show only my tickets
        <% end %>
      <% else %>
        <%= link_to tickets_path(:team=>@team, :status=>@status, :sort_by=>@sort_by, :show=>'mine') do %>
          <i class="glyphicon glyphicon-unchecked"></i>
          Show only my tickets
        <% end %>
    <% end %>
    </div>
  </div>
  <footer>
    <%= link_to "Log Out", logout_path %>
  </footer>
</nav>
<header>
  <a href="#" class="icon menu main-menu-button" title="Main menu"></a>

  <span>
    <% case @team
         when 'ios' then %>iOS
      <% when 'android' then %>Android
      <% when 'web' then %>Web
      <% when 'platform' then %>Platform
      <% when 'techops' then %>TechOp
      <% else %>All tickets
    <% end %>
    (<%= @bugs.length if @bugs.kind_of?(Array) %>)
  </span>

  <%= link_to "", new_ticket_path, :class => "icon new-ticket", :title => "New ticket" %>
</header>
<% if @bugs.kind_of?(Array) %>
  <% if @total > 0 %>
    <section class="filters">
      <div class="filter">
        <label for="sortby">Sort by</label>
        <%= select_tag("sortby", options_for_select([
          ['Last updated', 'newest'], ['State', 'state']], [@sort_by.capitalize, @sort_by])) %>
      </div>
      <div class="filter">
        <label for="status">Status</label>
        <%= select_tag("status", options_for_select([
          ['Opened tickets', 'opened'], ['Closed tickets', 'closed']], [@status.capitalize, @status])) %>
      </div>
    </section>
  <% end %>
  <% if @bugs.length == 0 %>
    <% if @total == 0 %>
    <div class="vcenter"><span>No tickets yet, <%= link_to "make your first ticket now!", new_ticket_path, :title => "New ticket" %></span></div>
    <% else %>
    <div class="vcenter"><span>No <%= @status %> tickets, please <%= link_to "go to the #{@opposite_status} ones", tickets_path(:team=>@team, :status=>@opposite_status, :sort_by=>@sort_by, :show=>@show), :title => "Change to #{@opposite_status} ones" %>.</span></div>
    <% end %>
  <% else %>
    <ul class="tickets">
    <% @bugs.each do |bug| %>
      <%
        severity = 'low'
        team = 'unknown'
        bug["labels"].each do |label|
          if Ticket.severities.include?(label['name'].downcase)
            severity = label["name"]
          else
            team = label["name"]
          end
        end
      %>
      <li class="ticket <%=severity%>">
        <%= link_to ticket_path(bug["id"]), :class=> "list-item" do %>
          <article>
            <div class="date">
              <%= Time.parse(bug["created_at"]).strftime("%A %d %b") %>

              <span class="last-update">
                (Last update <%= time_diff Time.parse(bug["updated_at"]) %> ago)
              </span>
            </div>
            <h2>
              <%= Rumoji.decode(bug["name"]) %>
            </h2>
          </article>
          <footer class="meta">
            Assigned to <em><%=team%></em> and has been <em><%= @alias_statuses[@statuses.index(bug["current_state"])] %></em>
          </footer>
        <% end %>
      </li>
    <% end %>
    </ul>
  <% end %>
<% else %>
  <%= @bugs["error"] %>
<% end %>
<script type="text/javascript">
  $(document).ready(function() {
    $('.main-menu-button').on('click', function() {
      $('#main-menu').toggleClass('hidden');
    });

    $('#sortby').on('change', function(evt) {
      window.location.href = "/tickets?team=<%= @team %>&sortby="+evt.target.options[evt.target.selectedIndex].value+"&status=<%= @status %>"
    });

    $('#status').on('change', function(evt) {
      window.location.href = "/tickets?team=<%= @team %>&status="+evt.target.options[evt.target.selectedIndex].value+"&sortby=<%= @sort_by %>"
    });
  });
</script>

app/views/tickets/show.html.erb
<% unless @ticket.nil? %>
  <header class="space-between">
    <span>
      <%= link_to tickets_path do %>
        <i class="icon back"></i>
        All tickets
      <% end %>
      / #<%= @ticket["id"] %>
    </span>

    <button id="edit-btn">Edit</button>
  </header>
  <main class="ticket <%= @ticket["severity"] %>">
    <div id="info">
      <em class="status"><%= @alias_statuses[@statuses.index(@ticket["current_state"])] %></em>
      <h1><%= @ticket["name"] %></h1>
      <section class="owner">
        <%
        unless @user.nil?
          name = @user["name"]
          image = gravatar_image_tag @user['email'], :class=>'avatar', :alt=> name
        else
          name = 'Nobody'
          image = image_tag(asset_path("logo.png"), :alt=> name, :class=>'avatar' )
        end
        %>
        <%= image %>
        <div>
          <div class="name">
            <%= name %>
          </div>
          <div class="date">
            <% time = Time.parse(@ticket["created_at"]) %>
            <%= time.strftime("%A #{time.day.ordinalize} %b %I:%M") %><%= time.strftime("%p").downcase %>
            <% if @ticket["created_at"] == @ticket["updated_at"] %>
            <span class="last-update">
              (<%= time_diff Time.parse(@ticket["updated_at"]) %> ago)
            </span>
            <% end %>
          </div>
        </div>
      </section>
      <section class="description">
        <%= @ticket["description"] %>
      </section>
      <% unless @ticket['attachments'].nil? or @ticket['attachments']['top'].nil? or @ticket['attachments']['top'].length == 0 %>
        <h2>Attachments</h2>
        <ul class="attachments">
          <% @ticket['attachments']['top'].each do |attachment| %>
          <li class="attachment">
            <%= link_to download_attachment_path(id: attachment["id"]), target: '_blank' do %>
              <span class="details">
                <%
                  url = 'http://placehold.it/72x53'
                  if attachment["thumbnailable"] == true and attachment["thumbnail_url"] != '#'
                    url = attachment["thumbnail_url"]
                  end
                %>
                <img src="<%= url %>">
                <%= attachment["filename"] %>
              </span>
              <i class="icon forward"></i>
            <% end %>
          </li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <section class="history">
      <ul id="list-items">
        <% last = nil %>
        <% @ticket["history"].each do |item| %>
        <li class="<%= item['kind'] %><% unless item["first_comment"].nil? %> hidden<% end %>">
          <% 
            unless item[:author].nil?
              author = item[:author]['person']['name']
              avatar = gravatar_image_tag item[:author]['person']['email'], :alt=> author
            else
              author = nil
              avatar = image_tag item['icon']
            end
          %>
          <%= avatar %>
          <div class="history-data">
            <% unless author.nil? %>
            <span>
              <%= author %>
            </span>
            <% end %>
            <div class="details">
              <% if item['kind'] == 'transaction' %>
                <%= simple_format(item["text"]) %>
              <% else %>
                <%= item["text"] %>
              <% end %>
            </div>
            <% unless @ticket['attachments'].nil? or @ticket['attachments'][item['id']].nil? %>
              <ul class="attachments">
                <% @ticket['attachments'][item['id']].each do |attachment| %>
                <li class="attachment">
                  <%= link_to download_attachment_path(id: attachment["id"]), target: '_blank' do %>
                    <span class="details">
                      <%
                        url = 'http://placehold.it/72x53'
                        if attachment["thumbnailable"] == true and attachment["thumbnail_url"] != '#'
                          url = attachment["thumbnail_url"]
                        end
                      %>
                      <img src="<%= url %>">
                      <%= attachment["filename"] %>
                    </span>
                    <i class="icon forward"></i>
                  <% end %>
                </li>
                <% end %>
              </ul>
            <% end %>
            <div class="meta">
              <%
                date = item["created_at"]
                time = Time.parse(date)
              %>
              <%= time.strftime("%A #{time.day.ordinalize} %b %I:%M") %><%= time.strftime("%p").downcase %>
              <% unless last.nil? %>
               (+<%= time_diff last, time %>)
              <% end %>
            </div>
          </div>
        </li>
        <% last = time %>
        <% end %>
      </ul>
      <div id="form-comment-wrapper">
        <%= form_tag("/tickets/comment", method: :post, id: 'form-comment') do  %>
          <%= hidden_field(:ticket, :id, :value => @ticket["id"]) %>
          <%= hidden_field(:ticket, :project_id, :value => @ticket["project_id"]) %>
          <div class="form-group">
            <%= text_area_tag("comment[text]", @comment['text']||"", :class => "form-control", :placeholder => "Comment", 'required'=>true, maxlength: Ticket.max_comment) %>
            <% unless @errors.nil? or @errors.class.to_s != 'Array' %>
              <% @errors.each do |error| %>
                <% if error['field'] == 'comment' %>
                  <div id="comment_error" class="error"><%= error['problem'] %></div>
                <% end %>
              <% end %>
            <% end %>
            <div id="comment_error" class="error hidden">The comment cannot be empty</div>
          </div>
          <%= hidden_field_tag("comment[file_attachments]", @comment['attachments']||"[]" ) %>
          <% unless @comment['attachments'].nil? or @comment['attachments'].length==0 %>
          <div class="form-group">
            The following files were already uploaded: 
            <% first = true
              comments = ActiveSupport::JSON.decode(@comment['attachments'])
              comments.each do |att| %>
              <% if first
                  first = false
                else %>
                ,
              <% end %>
              <%= att['filename'] %>
            <% end %>
            </div>
          <% end %>
        <% end %>
        <%= form_tag("/tickets/upload", method: :post, id: 'fileuploads', enctype: "multipart/form-data", remote: true, class: "ticket") do %>
            <div class="form-group two-cols noborder">
              <label for="attachments">Attachment(s)</label>
              <ul id="files-attached">
                <li id="add-file" class="clickable">
                  <i class="icon plus"></i> Add file
                </li>
              </ul>
              <%= file_field_tag "attachments", :multiple=> true, name: 'attachments[]', class: 'hidden' %>
            </div>

            <div id="progress" class="hidden">
              <div class="bar" style="width: 0%;"></div>
            </div>
        <% end %>
        <div class="form-group noborder outform">
          <%= button_tag('Submit comment', :class => "btn btn-primary", :id => "submit-comment") %>
        </div>
      </div>
    </section>
  </main>

  <script type="text/javascript">
    $('#edit-btn').on('click', function(){
      window.location.href = window.location.href+'/edit'
    })
    var files = [];

    $('#add-file').on('click', function(evt) {
      $('#attachments').trigger('click');
    });

    $("#attachments").fileupload({
      dataType: 'json',
      add: function (e, data) {
        var template = $('#files-attached');
        for (var idx=0; idx<data.files.length; idx++) {
          files.push(data.files[idx]);
          var t = $('<li/>').text(data.files[idx].name).prependTo(template);
          var redCross = $('<i class="icon red-cross"/>')
          redCross.prependTo(t);

          // attach the click event to delete the file from the list
          $(redCross).on('click', function(evt) {
            var filename = this.nextSibling.textContent;

            $(redCross).unbind('click');

            // remove the file from the list
            files = files.map( function(item) {
              if (item.name!==filename)
                return item;
            }).filter(function(item) { return item!= undefined; });

            // remove node in view
            t.remove();
          });
        }
        data.context = template;

      },
      done: function(e, data) {
        console.log('done!', arguments);
      },
      url: "/tickets/upload",
      progress: function (e, data) {
        var progress = parseInt(data.loaded / data.total * 100, 10);
        $('#progress .bar').css(
            'width',
            progress + '%'
        );
      }
   });

   $('#submit-comment').on('click', function(e) {
      // disable submit button
      $(e.target).prop('disabled', 'disabled');

      if ($("#comment_text").val().trim() === "") {
        $("#comment_error").removeClass('hidden');
        $(e.target).prop('disabled', '');
      } else {
        $("#comment_error").addClass('hidden');

        if (files.length > 0) {
          $('#progress').removeClass("hidden");
          $("#attachments").fileupload('send', {files: files})
            .success(function(data, status) {
              console.log('sent', arguments);
              var attchs = $('#comment_file_attachments').val();

              if(attchs == "") {
                attchs = [];
              } else {
                attchs = JSON.parse($('#comment_file_attachments').val());  
              }

              attchs = attchs.concat(arguments[0]);
              $('#comment_file_attachments').val(JSON.stringify(attchs));
              $('#form-comment').submit();
            })
            .error(function(data) {
              console.log('err', arguments);
              $(e.target).prop('disabled', '');
              $('#progress').addClass("hidden");
            })
            .complete(function(data) { console.log('complete', arguments); });
        } else {
          $('#form-comment').submit();
        }
      }

      return false;
   });

  </script>
<% else %>
  <header class="right">
    <span>
      <%= link_to tickets_path do %>
        <i class="icon back"></i>
        All tickets
      <% end %>
      / Not found
    </span>

  </header>
  <main class="ticket">
    <h1>Ticket not found</h1>
  </main>
<% end %>